### PR TITLE
Adds a readme on querying salesforce from heroku app

### PR DESCRIPTION
**Pull request by lucymonie**
@nelsonic, I have done a readme about methods of querying salesforce to allow data requests from a heroku app. 

My impression is that the most suitable methods are Heroku Connect or a Salesforce REST API. My understanding is that these are available with the Heroku Enterprise version but not with the free or hobby versions.

Would you have any advice or opinion on whether these are good options?

This addresses #45 and #59

### CODE REVIEW

**Comment by msachi** [comment]
Thanks @lucymonie, really good work! :)

**Comment by nelsonic** [comment]
@lucymonie looks good. I would _always_ go with the REST API: https://developer.salesforce.com/page/REST_API because you can get _exactly_ what you need.
(_requires a bit more setup but gives you more insight_)

**Review by nelsonic — COMMENTED** [review]
@lucymonie this is a _really_ good summary of the options. While I have typically used the REST API in the past because it offers "more control", Heroku Connect is a _really_ good service so if your product owner is willing to pay for "Enterprise" then you should use it! 👍 
(_REST API requires a bit more setup/OAuth but gives you more insight into the data stored by Salesforce..._)

**Comment by lucymonie** [comment]
@msachi, I am now getting some sort of response back from Salesforce but I think my queries are off. Any thoughts @nelsonic?

Response looks like this:
`[ Record {
    attributes: 
     { type: 'Account',
       url: '/services/data/v38.0/sobjects/Account/0010S00000332aQQAQ' },
    _changed: [],
    _previous: {},
    _fields: { id: '0010S00000332aQQAQ', name: 'Test Service' } } ]`

**Comment by nelsonic** [comment]
@lucymonie that response looks fine. what did you _ask_ for? :-)

**Comment by lucymonie** [comment]
Thanks @nelsonic! I wanted to ask for specific information about a client in the system, but I'm not clear how to write queries that will do that - all the examples I found were along the lines of 
`query: 'SELECT Id, Name FROM Account'`

But the response isn't very edifying. I'm not clear how I can access a specific client record. The response looks like it's just getting the name and ID of the sandbox we're using rather than a client. Our Centrepoint sandbox is currently set up with a single client record for us to query. 

Below is a link to the code I have so far: 
https://github.com/lucy-marko/centrepoint/blob/35d6e43163f5a7d102b3553c06a8b3098e226749/src/routes/salesforce.js

I am going to do some googling on how to write this sort of query, but if you can point me towards any particular resources I would so much appreciate it!

**Comment by nelsonic** [comment]
@lucymonie you are _correct_ you are getting a `default` or "dummy" response from the SF sandbox.
If you want to get a specific Account record you need to specify the `Id` in your query.

**Pull request closed without merging**
